---
  header_logo_url: http://Phasmida.archive.speciesfile.org/HomePage/Phasmida/img_Logo/SiteLogo.jpg
  header_logo_text: Phasmida Species File
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about
