---
metadata:
  - name: description
    content: The Phasmida Species File is a taxonomic, nomenclatural, and bibliographic database of the stick and leaf insects of the world, including all extant and fossil taxa.
  - name: keywords
    content: taxonomy, species, Species File Group, Phasmida, stick insect, leaf insect, taxonpages, Phasmida Species File
  - name: robots
    content: follow
