---
  project_name: "Phasmida Species File"
  project_citation: "Phasmida Species File Online"
  project_authors:  "Brock PD, Büscher TH, Baker E."
  project_url: "https://phasmida.speciesfile.org"
  project_old_url: "http://phasmida.archive.speciesfile.org" 
  focal_taxon: "Phasmida"
  focal_taxon_common_name: "stick and leaf insects"
  contact_email: "pauldbrock@btinternet.com"
